# Generated by Django 4.1.4 on 2022-12-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_catbreeds_id_breeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catbreeds',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='catbreeds',
            name='temperament',
            field=models.TextField(verbose_name='Temperamento'),
        ),
    ]
